name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      WAIT_TIME: ${{ secrets.WAIT_TIME }}
      REVIEWER: ${{ secrets.REVIEWER }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Display Environment Variables
        run: |
          echo "Wait time is $WAIT_TIME"
          echo "Reviewer is $REVIEWER"
          # Be careful not to print SECRET_KEY publicly!
        
      - name: Simulate Wait (Using WAIT_TIME env variable)
        run: |
          echo "Waiting for $WAIT_TIME seconds..."
          sleep $WAIT_TIME
          
      - name: Example Deployment Step
        run: |
          echo "Deploying app..."
          # Your deploy commands go here
          
      - name: Notify Reviewer
        run: |
          echo "Notifying reviewer $REVIEWER"
          # You can add custom logic here (e.g., send notification)
